// AUTO-GENERATED by flux-control/scripts/introspect.ts — do not edit by hand

export interface EnvVar {
  project_id: string;
  key: string;
  value: string;
  updated_at: string | null;
}

export interface Function {
  id: string | null;
  project_id: string | null;
  name: string;
  latest_artifact_id: string | null;
  created_at: string | null;
  access_policy: string | null;
  webhook_secret: string | null;
  rate_limit_rpm: number | null;
  max_duration_ms: number | null;
}

export interface Member {
  user_id: string;
  org_id: string;
  role: string | null;
}

export interface Org {
  id: string | null;
  name: string;
  created_at: string | null;
  slug: string | null;
}

export interface Project {
  id: string | null;
  org_id: string | null;
  name: string;
  base_domain: string | null;
  created_at: string | null;
  slug: string | null;
}

export interface Route {
  id: string | null;
  project_id: string | null;
  method: string;
  path: string;
  function_id: string | null;
  created_at: string | null;
}

export interface ServiceToken {
  id: string | null;
  org_id: string;
  project_id: string;
  token_hash: string;
  created_at: string | null;
  revoked: boolean | null;
  last_used_at: string | null;
  name: string | null;
}

export interface UserAccount {
  id: string | null;
  user_id: string;
  provider: string;
  provider_id: string;
  created_at: string | null;
}

export interface User {
  id: string | null;
  email: string;
  created_at: string | null;
  password: string | null;
}

export interface Waitlist {
  id: string | null;
  email: string;
  source: string | null;
  created_at: string | null;
}

export interface Webhook {
  id: string | null;
  project_id: string | null;
  url: string;
  created_at: string | null;
}

export interface Checkpoint {
  execution_id: string;
  call_index: number;
  boundary: string;
  url: string | null;
  method: string | null;
  request: Record<string, unknown> | null;
  response: Record<string, unknown> | null;
  duration_ms: number | null;
  created_at: string | null;
  org_id: string | null;
}

export interface ExecutionConsoleLog {
  execution_id: string;
  seq: number;
  level: string;
  message: string;
  created_at: string | null;
  org_id: string | null;
}

export interface Execution {
  id: string;
  request_id: string;
  project_id: string | null;
  method: string;
  path: string;
  status: string;
  request: Record<string, unknown> | null;
  response: Record<string, unknown> | null;
  error: string | null;
  code_sha: string;
  started_at: string | null;
  duration_ms: number | null;
  org_id: string | null;
  token_id: string | null;
  request_method: string | null;
  request_headers: Record<string, unknown> | null;
  request_body: string | null;
  response_status: number | null;
  response_body: string | null;
  client_ip: string | null;
  user_agent: string | null;
  error_stack: string | null;
  error_fingerprint: string | null;
}

export interface Issue {
  id: string | null;
  function_id: string;
  fingerprint: string;
  title: string;
  first_seen: string | null;
  last_seen: string | null;
  occurrence_count: number | null;
  unique_ips: number | null;
  unique_tokens: number | null;
  status: string | null;
  created_at: string | null;
  sample_stack: string | null;
  sample_message: string | null;
  sample_execution_id: string | null;
}

export interface Span {
  id: string | null;
  execution_id: string;
  type: string;
  label: string | null;
  start_ms: number;
  duration_ms: number;
  metadata: Record<string, unknown> | null;
}
