// AUTO-GENERATED by flux-control/scripts/introspect.ts — do not edit by hand

export interface Function {
  id: string | null;
  project_id: string | null;
  name: string;
  latest_artifact_id: string | null;
  access_policy: string;
  webhook_secret: string | null;
  rate_limit_rpm: number;
  max_duration_ms: number;
  created_at: string | null;
}

export interface Member {
  user_id: string;
  org_id: string;
  role: string | null;
}

export interface Org {
  id: string | null;
  name: string;
  created_at: string | null;
}

export interface Project {
  id: string | null;
  org_id: string | null;
  name: string;
  base_domain: string | null;
  created_at: string | null;
}

export interface Route {
  id: string | null;
  project_id: string | null;
  method: string;
  path: string;
  function_id: string | null;
  created_at: string | null;
}

export interface ServiceToken {
  id: string | null;
  org_id: string;
  project_id: string;
  token_hash: string;
  created_at: string | null;
  revoked: boolean | null;
  last_used_at: string | null;
}

export interface User {
  id: string | null;
  email: string;
  created_at: string | null;
  password: string | null;
  provider: string | null;
  provider_id: string | null;
}

export interface Waitlist {
  id: string | null;
  email: string;
  source: string | null;
  created_at: string | null;
}

export interface Webhook {
  id: string | null;
  project_id: string | null;
  url: string;
  created_at: string | null;
}

export interface Checkpoint {
  execution_id: string;
  call_index: number;
  boundary: string;
  url: string | null;
  method: string | null;
  request: Record<string, unknown> | null;
  response: Record<string, unknown> | null;
  duration_ms: number | null;
  created_at: string | null;
  org_id: string | null;
}

export interface ExecutionConsoleLog {
  execution_id: string;
  seq: number;
  level: string;
  message: string;
  created_at: string | null;
  org_id: string | null;
}

export interface Execution {
  id: string;
  request_id: string;
  project_id: string | null;
  method: string;
  path: string;
  status: string;
  request: Record<string, unknown> | null;
  response: Record<string, unknown> | null;
  error: string | null;
  code_sha: string;
  started_at: string | null;
  duration_ms: number | null;
  org_id: string | null;
}
